//
//  SettingsIcons.h
//  Trivit
//
//  Created by Pieterjan Criel - Wouter Devriendt on 30/12/14.
//  Copyright (c) 2014 Ballooninc. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface SettingsIcons : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* feedbackTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tutorialTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* trashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas1Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas2Targets;

// Drawing Methods
+ (void)drawFeedback;
+ (void)drawTutorial;
+ (void)drawTrash;
+ (void)drawCanvas1;
+ (void)drawCanvas2;

// Generated Images
+ (UIImage*)imageOfFeedback;
+ (UIImage*)imageOfTutorial;
+ (UIImage*)imageOfTrash;
+ (UIImage*)imageOfCanvas1;
+ (UIImage*)imageOfCanvas2;
+ (UIImage *)imageWithImage:(UIImage *)image scaledToSize: (CGRect)rect;
@end
