//
//  SettingsIcons.m
//  Trivit
//
//  Created by Pieterjan Criel - Wouter Devriendt on 30/12/14.
//  Copyright (c) 2014 Ballooninc. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "SettingsIcons.h"


@implementation SettingsIcons

#pragma mark Cache

static UIImage* _imageOfFeedback = nil;
static UIImage* _imageOfTutorial = nil;
static UIImage* _imageOfTrash = nil;
static UIImage* _imageOfCanvas1 = nil;
static UIImage* _imageOfCanvas2 = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawFeedback
{
    //// Color Declarations
    UIColor* color0 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Group
    {
        //// Bezier 4 Drawing
        UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
        [bezier4Path moveToPoint: CGPointMake(49.83, 20.48)];
        [bezier4Path addCurveToPoint: CGPointMake(49.83, 20.47) controlPoint1: CGPointMake(49.83, 20.48) controlPoint2: CGPointMake(49.83, 20.48)];
        [bezier4Path addCurveToPoint: CGPointMake(49.79, 20.33) controlPoint1: CGPointMake(49.82, 20.42) controlPoint2: CGPointMake(49.81, 20.38)];
        [bezier4Path addCurveToPoint: CGPointMake(49.77, 20.29) controlPoint1: CGPointMake(49.78, 20.32) controlPoint2: CGPointMake(49.77, 20.31)];
        [bezier4Path addCurveToPoint: CGPointMake(49.71, 20.2) controlPoint1: CGPointMake(49.75, 20.26) controlPoint2: CGPointMake(49.73, 20.23)];
        [bezier4Path addCurveToPoint: CGPointMake(49.68, 20.16) controlPoint1: CGPointMake(49.7, 20.19) controlPoint2: CGPointMake(49.69, 20.17)];
        [bezier4Path addCurveToPoint: CGPointMake(49.61, 20.09) controlPoint1: CGPointMake(49.66, 20.13) controlPoint2: CGPointMake(49.64, 20.11)];
        [bezier4Path addCurveToPoint: CGPointMake(49.6, 20.07) controlPoint1: CGPointMake(49.61, 20.08) controlPoint2: CGPointMake(49.6, 20.08)];
        [bezier4Path addLineToPoint: CGPointMake(41.91, 13.26)];
        [bezier4Path addLineToPoint: CGPointMake(41.91, 8.36)];
        [bezier4Path addCurveToPoint: CGPointMake(41.16, 7.62) controlPoint1: CGPointMake(41.91, 7.95) controlPoint2: CGPointMake(41.57, 7.62)];
        [bezier4Path addLineToPoint: CGPointMake(35.54, 7.62)];
        [bezier4Path addLineToPoint: CGPointMake(28.73, 1.58)];
        [bezier4Path addCurveToPoint: CGPointMake(21.27, 1.58) controlPoint1: CGPointMake(26.67, -0.29) controlPoint2: CGPointMake(23.32, -0.29)];
        [bezier4Path addLineToPoint: CGPointMake(14.46, 7.62)];
        [bezier4Path addLineToPoint: CGPointMake(8.84, 7.62)];
        [bezier4Path addCurveToPoint: CGPointMake(8.09, 8.36) controlPoint1: CGPointMake(8.42, 7.62) controlPoint2: CGPointMake(8.09, 7.95)];
        [bezier4Path addLineToPoint: CGPointMake(8.09, 13.26)];
        [bezier4Path addLineToPoint: CGPointMake(0.4, 20.07)];
        [bezier4Path addCurveToPoint: CGPointMake(0.31, 20.16) controlPoint1: CGPointMake(0.37, 20.1) controlPoint2: CGPointMake(0.34, 20.13)];
        [bezier4Path addLineToPoint: CGPointMake(0.31, 20.16)];
        [bezier4Path addLineToPoint: CGPointMake(0.31, 20.16)];
        [bezier4Path addCurveToPoint: CGPointMake(0.25, 20.26) controlPoint1: CGPointMake(0.29, 20.19) controlPoint2: CGPointMake(0.27, 20.23)];
        [bezier4Path addLineToPoint: CGPointMake(0.25, 20.26)];
        [bezier4Path addCurveToPoint: CGPointMake(0.15, 20.61) controlPoint1: CGPointMake(0.19, 20.37) controlPoint2: CGPointMake(0.15, 20.49)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 20.61)];
        [bezier4Path addCurveToPoint: CGPointMake(0.15, 20.61) controlPoint1: CGPointMake(0.15, 20.61) controlPoint2: CGPointMake(0.15, 20.61)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 20.61)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 20.62)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 20.62)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 20.62)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 20.62)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 20.62)];
        [bezier4Path addLineToPoint: CGPointMake(0.15, 49.1)];
        [bezier4Path addCurveToPoint: CGPointMake(0.9, 49.83) controlPoint1: CGPointMake(0.15, 49.5) controlPoint2: CGPointMake(0.49, 49.83)];
        [bezier4Path addLineToPoint: CGPointMake(49.1, 49.83)];
        [bezier4Path addCurveToPoint: CGPointMake(49.85, 49.1) controlPoint1: CGPointMake(49.51, 49.83) controlPoint2: CGPointMake(49.85, 49.5)];
        [bezier4Path addLineToPoint: CGPointMake(49.85, 20.62)];
        [bezier4Path addCurveToPoint: CGPointMake(49.83, 20.48) controlPoint1: CGPointMake(49.85, 20.57) controlPoint2: CGPointMake(49.84, 20.53)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(47.96, 20.61)];
        [bezier4Path addLineToPoint: CGPointMake(41.91, 25.73)];
        [bezier4Path addLineToPoint: CGPointMake(41.91, 15.24)];
        [bezier4Path addLineToPoint: CGPointMake(47.96, 20.61)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(22.28, 2.67)];
        [bezier4Path addCurveToPoint: CGPointMake(27.72, 2.67) controlPoint1: CGPointMake(23.78, 1.31) controlPoint2: CGPointMake(26.22, 1.31)];
        [bezier4Path addLineToPoint: CGPointMake(33.3, 7.62)];
        [bezier4Path addLineToPoint: CGPointMake(16.69, 7.62)];
        [bezier4Path addLineToPoint: CGPointMake(22.28, 2.67)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(9.59, 9.09)];
        [bezier4Path addLineToPoint: CGPointMake(40.41, 9.09)];
        [bezier4Path addLineToPoint: CGPointMake(40.41, 27)];
        [bezier4Path addLineToPoint: CGPointMake(33.2, 33.1)];
        [bezier4Path addLineToPoint: CGPointMake(28.44, 29.45)];
        [bezier4Path addCurveToPoint: CGPointMake(21.57, 29.44) controlPoint1: CGPointMake(26.51, 27.88) controlPoint2: CGPointMake(23.49, 27.88)];
        [bezier4Path addLineToPoint: CGPointMake(16.8, 33.1)];
        [bezier4Path addLineToPoint: CGPointMake(9.59, 27)];
        [bezier4Path addLineToPoint: CGPointMake(9.59, 9.09)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(8.09, 15.24)];
        [bezier4Path addLineToPoint: CGPointMake(8.09, 25.73)];
        [bezier4Path addLineToPoint: CGPointMake(2.03, 20.61)];
        [bezier4Path addLineToPoint: CGPointMake(8.09, 15.24)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(1.65, 22.23)];
        [bezier4Path addLineToPoint: CGPointMake(8.31, 27.86)];
        [bezier4Path addCurveToPoint: CGPointMake(8.39, 27.93) controlPoint1: CGPointMake(8.33, 27.89) controlPoint2: CGPointMake(8.36, 27.91)];
        [bezier4Path addLineToPoint: CGPointMake(15.6, 34.03)];
        [bezier4Path addLineToPoint: CGPointMake(1.65, 44.74)];
        [bezier4Path addLineToPoint: CGPointMake(1.65, 22.23)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(48.35, 48.36)];
        [bezier4Path addLineToPoint: CGPointMake(1.65, 48.36)];
        [bezier4Path addLineToPoint: CGPointMake(1.65, 46.61)];
        [bezier4Path addLineToPoint: CGPointMake(22.51, 30.59)];
        [bezier4Path addCurveToPoint: CGPointMake(27.5, 30.6) controlPoint1: CGPointMake(23.88, 29.47) controlPoint2: CGPointMake(26.12, 29.47)];
        [bezier4Path addLineToPoint: CGPointMake(48.35, 46.61)];
        [bezier4Path addLineToPoint: CGPointMake(48.35, 48.36)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(34.4, 34.03)];
        [bezier4Path addLineToPoint: CGPointMake(48.35, 22.23)];
        [bezier4Path addLineToPoint: CGPointMake(48.35, 44.74)];
        [bezier4Path addLineToPoint: CGPointMake(34.4, 34.03)];
        [bezier4Path closePath];
        bezier4Path.miterLimit = 4;
        
        [color0 setFill];
        [bezier4Path fill];
        
        
        //// LINE_52_
        {
            //// Group 3
            {
                //// Bezier 6 Drawing
                UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
                [bezier6Path moveToPoint: CGPointMake(25, 26.62)];
                [bezier6Path addCurveToPoint: CGPointMake(24.32, 25.84) controlPoint1: CGPointMake(24.62, 26.62) controlPoint2: CGPointMake(24.32, 26.27)];
                [bezier6Path addLineToPoint: CGPointMake(24.32, 15.12)];
                [bezier6Path addLineToPoint: CGPointMake(21.75, 18.07)];
                [bezier6Path addCurveToPoint: CGPointMake(20.78, 18.07) controlPoint1: CGPointMake(21.48, 18.37) controlPoint2: CGPointMake(21.05, 18.37)];
                [bezier6Path addCurveToPoint: CGPointMake(20.78, 16.96) controlPoint1: CGPointMake(20.51, 17.76) controlPoint2: CGPointMake(20.51, 17.26)];
                [bezier6Path addLineToPoint: CGPointMake(24.52, 12.68)];
                [bezier6Path addCurveToPoint: CGPointMake(24.74, 12.51) controlPoint1: CGPointMake(24.58, 12.61) controlPoint2: CGPointMake(24.65, 12.55)];
                [bezier6Path addCurveToPoint: CGPointMake(25.09, 12.45) controlPoint1: CGPointMake(24.85, 12.45) controlPoint2: CGPointMake(24.97, 12.44)];
                [bezier6Path addLineToPoint: CGPointMake(25.09, 12.45)];
                [bezier6Path addLineToPoint: CGPointMake(25.09, 12.45)];
                [bezier6Path addLineToPoint: CGPointMake(25.09, 12.45)];
                [bezier6Path addLineToPoint: CGPointMake(25.09, 12.45)];
                [bezier6Path addCurveToPoint: CGPointMake(25.16, 12.47) controlPoint1: CGPointMake(25.12, 12.46) controlPoint2: CGPointMake(25.14, 12.46)];
                [bezier6Path addLineToPoint: CGPointMake(25.16, 12.47)];
                [bezier6Path addLineToPoint: CGPointMake(25.16, 12.47)];
                [bezier6Path addCurveToPoint: CGPointMake(25.48, 12.67) controlPoint1: CGPointMake(25.28, 12.5) controlPoint2: CGPointMake(25.39, 12.57)];
                [bezier6Path addLineToPoint: CGPointMake(25.48, 12.67)];
                [bezier6Path addLineToPoint: CGPointMake(25.48, 12.67)];
                [bezier6Path addLineToPoint: CGPointMake(25.48, 12.68)];
                [bezier6Path addLineToPoint: CGPointMake(25.49, 12.68)];
                [bezier6Path addLineToPoint: CGPointMake(25.49, 12.68)];
                [bezier6Path addLineToPoint: CGPointMake(29.22, 16.96)];
                [bezier6Path addCurveToPoint: CGPointMake(29.42, 17.51) controlPoint1: CGPointMake(29.36, 17.11) controlPoint2: CGPointMake(29.42, 17.31)];
                [bezier6Path addCurveToPoint: CGPointMake(29.22, 18.06) controlPoint1: CGPointMake(29.42, 17.71) controlPoint2: CGPointMake(29.36, 17.91)];
                [bezier6Path addCurveToPoint: CGPointMake(28.25, 18.06) controlPoint1: CGPointMake(28.95, 18.37) controlPoint2: CGPointMake(28.52, 18.37)];
                [bezier6Path addLineToPoint: CGPointMake(25.69, 15.12)];
                [bezier6Path addLineToPoint: CGPointMake(25.69, 25.84)];
                [bezier6Path addCurveToPoint: CGPointMake(25, 26.62) controlPoint1: CGPointMake(25.69, 26.27) controlPoint2: CGPointMake(25.38, 26.62)];
                [bezier6Path closePath];
                bezier6Path.miterLimit = 4;
                
                [color2 setFill];
                [bezier6Path fill];
            }
        }
    }
}

+ (void)drawTutorial
{
    //// Color Declarations
    UIColor* color3 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color4 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Bezier 4 Drawing
    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
    [bezier4Path moveToPoint: CGPointMake(79.86, 169.79)];
    [bezier4Path addLineToPoint: CGPointMake(79.86, 157.2)];
    [bezier4Path addCurveToPoint: CGPointMake(69.06, 145.52) controlPoint1: CGPointMake(79.91, 151.16) controlPoint2: CGPointMake(75.06, 145.93)];
    [bezier4Path addLineToPoint: CGPointMake(24.46, 142.13)];
    [bezier4Path addCurveToPoint: CGPointMake(22.32, 143.97) controlPoint1: CGPointMake(23.36, 142.05) controlPoint2: CGPointMake(22.4, 142.87)];
    [bezier4Path addCurveToPoint: CGPointMake(24.16, 146.12) controlPoint1: CGPointMake(22.23, 145.07) controlPoint2: CGPointMake(23.06, 146.03)];
    [bezier4Path addLineToPoint: CGPointMake(68.77, 149.51)];
    [bezier4Path addCurveToPoint: CGPointMake(75.86, 157.18) controlPoint1: CGPointMake(72.72, 149.78) controlPoint2: CGPointMake(75.9, 153.21)];
    [bezier4Path addLineToPoint: CGPointMake(75.86, 169.79)];
    [bezier4Path addCurveToPoint: CGPointMake(73.44, 173.71) controlPoint1: CGPointMake(74.43, 170.52) controlPoint2: CGPointMake(73.44, 171.99)];
    [bezier4Path addCurveToPoint: CGPointMake(77.86, 186.13) controlPoint1: CGPointMake(73.44, 176.15) controlPoint2: CGPointMake(75.42, 186.13)];
    [bezier4Path addCurveToPoint: CGPointMake(82.28, 173.71) controlPoint1: CGPointMake(80.3, 186.13) controlPoint2: CGPointMake(82.28, 176.15)];
    [bezier4Path addCurveToPoint: CGPointMake(79.86, 169.79) controlPoint1: CGPointMake(82.28, 171.99) controlPoint2: CGPointMake(81.29, 170.52)];
    [bezier4Path closePath];
    bezier4Path.miterLimit = 4;
    
    [UIColor.blackColor setFill];
    [bezier4Path fill];
    
    
    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(49.25, 19.72)];
        [bezier2Path addLineToPoint: CGPointMake(25.14, 12.87)];
        [bezier2Path addCurveToPoint: CGPointMake(24.75, 12.87) controlPoint1: CGPointMake(25.02, 12.84) controlPoint2: CGPointMake(24.88, 12.84)];
        [bezier2Path addLineToPoint: CGPointMake(0.65, 19.72)];
        [bezier2Path addCurveToPoint: CGPointMake(0.13, 20.4) controlPoint1: CGPointMake(0.34, 19.8) controlPoint2: CGPointMake(0.13, 20.08)];
        [bezier2Path addCurveToPoint: CGPointMake(0.65, 21.08) controlPoint1: CGPointMake(0.13, 20.71) controlPoint2: CGPointMake(0.34, 20.99)];
        [bezier2Path addLineToPoint: CGPointMake(9.78, 23.67)];
        [bezier2Path addLineToPoint: CGPointMake(9.78, 29.53)];
        [bezier2Path addCurveToPoint: CGPointMake(24.95, 34.68) controlPoint1: CGPointMake(9.78, 32.87) controlPoint2: CGPointMake(17.59, 34.68)];
        [bezier2Path addCurveToPoint: CGPointMake(40.12, 29.53) controlPoint1: CGPointMake(32.31, 34.68) controlPoint2: CGPointMake(40.12, 32.88)];
        [bezier2Path addLineToPoint: CGPointMake(40.12, 23.67)];
        [bezier2Path addLineToPoint: CGPointMake(49.25, 21.08)];
        [bezier2Path addCurveToPoint: CGPointMake(49.77, 20.4) controlPoint1: CGPointMake(49.56, 20.99) controlPoint2: CGPointMake(49.77, 20.71)];
        [bezier2Path addCurveToPoint: CGPointMake(49.25, 19.72) controlPoint1: CGPointMake(49.77, 20.08) controlPoint2: CGPointMake(49.56, 19.8)];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(38.7, 29.53)];
        [bezier2Path addCurveToPoint: CGPointMake(24.95, 33.27) controlPoint1: CGPointMake(38.7, 31.09) controlPoint2: CGPointMake(33.47, 33.27)];
        [bezier2Path addCurveToPoint: CGPointMake(11.2, 29.53) controlPoint1: CGPointMake(16.43, 33.27) controlPoint2: CGPointMake(11.2, 31.09)];
        [bezier2Path addLineToPoint: CGPointMake(11.2, 24.07)];
        [bezier2Path addLineToPoint: CGPointMake(24.75, 27.92)];
        [bezier2Path addCurveToPoint: CGPointMake(24.95, 27.94) controlPoint1: CGPointMake(24.82, 27.94) controlPoint2: CGPointMake(24.88, 27.94)];
        [bezier2Path addCurveToPoint: CGPointMake(25.14, 27.92) controlPoint1: CGPointMake(25.01, 27.94) controlPoint2: CGPointMake(25.08, 27.94)];
        [bezier2Path addLineToPoint: CGPointMake(38.7, 24.07)];
        [bezier2Path addLineToPoint: CGPointMake(38.7, 29.53)];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(24.95, 26.5)];
        [bezier2Path addLineToPoint: CGPointMake(3.43, 20.4)];
        [bezier2Path addLineToPoint: CGPointMake(24.95, 14.29)];
        [bezier2Path addLineToPoint: CGPointMake(46.47, 20.4)];
        [bezier2Path addLineToPoint: CGPointMake(24.95, 26.5)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;
        
        [color4 setFill];
        [bezier2Path fill];
        
        
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(44.7, 29.46)];
        [bezierPath addLineToPoint: CGPointMake(44.7, 25.01)];
        [bezierPath addCurveToPoint: CGPointMake(40.86, 20.89) controlPoint1: CGPointMake(44.71, 22.88) controlPoint2: CGPointMake(42.99, 21.03)];
        [bezierPath addLineToPoint: CGPointMake(25, 19.69)];
        [bezierPath addCurveToPoint: CGPointMake(24.24, 20.34) controlPoint1: CGPointMake(24.61, 19.66) controlPoint2: CGPointMake(24.27, 19.95)];
        [bezierPath addCurveToPoint: CGPointMake(24.89, 21.1) controlPoint1: CGPointMake(24.21, 20.73) controlPoint2: CGPointMake(24.5, 21.07)];
        [bezierPath addLineToPoint: CGPointMake(40.75, 22.3)];
        [bezierPath addCurveToPoint: CGPointMake(43.27, 25.01) controlPoint1: CGPointMake(42.16, 22.39) controlPoint2: CGPointMake(43.29, 23.6)];
        [bezierPath addLineToPoint: CGPointMake(43.27, 29.46)];
        [bezierPath addCurveToPoint: CGPointMake(42.41, 30.84) controlPoint1: CGPointMake(42.77, 29.72) controlPoint2: CGPointMake(42.41, 30.24)];
        [bezierPath addCurveToPoint: CGPointMake(43.98, 35.23) controlPoint1: CGPointMake(42.41, 31.71) controlPoint2: CGPointMake(43.12, 35.23)];
        [bezierPath addCurveToPoint: CGPointMake(45.56, 30.84) controlPoint1: CGPointMake(44.85, 35.23) controlPoint2: CGPointMake(45.56, 31.71)];
        [bezierPath addCurveToPoint: CGPointMake(44.7, 29.46) controlPoint1: CGPointMake(45.56, 30.24) controlPoint2: CGPointMake(45.2, 29.72)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;
        
        [color3 setFill];
        [bezierPath fill];
    }
}

+ (void)drawTrash
{
    //// Color Declarations
    UIColor* color5 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color6 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color7 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color8 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Group 5
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(47.66, 8.68)];
        [bezier2Path addCurveToPoint: CGPointMake(44.18, 5.17) controlPoint1: CGPointMake(47.66, 6.74) controlPoint2: CGPointMake(46.1, 5.17)];
        [bezier2Path addLineToPoint: CGPointMake(43.19, 5.17)];
        [bezier2Path addCurveToPoint: CGPointMake(39.79, 2.4) controlPoint1: CGPointMake(42.85, 3.59) controlPoint2: CGPointMake(41.45, 2.4)];
        [bezier2Path addLineToPoint: CGPointMake(30.1, 2.4)];
        [bezier2Path addLineToPoint: CGPointMake(30.1, 1.85)];
        [bezier2Path addCurveToPoint: CGPointMake(30.08, 1.7) controlPoint1: CGPointMake(30.1, 1.8) controlPoint2: CGPointMake(30.09, 1.75)];
        [bezier2Path addCurveToPoint: CGPointMake(28.26, 0) controlPoint1: CGPointMake(30, 0.75) controlPoint2: CGPointMake(29.22, 0)];
        [bezier2Path addLineToPoint: CGPointMake(21.67, 0)];
        [bezier2Path addCurveToPoint: CGPointMake(19.85, 1.7) controlPoint1: CGPointMake(20.71, 0) controlPoint2: CGPointMake(19.93, 0.75)];
        [bezier2Path addCurveToPoint: CGPointMake(19.84, 1.85) controlPoint1: CGPointMake(19.84, 1.75) controlPoint2: CGPointMake(19.84, 1.8)];
        [bezier2Path addLineToPoint: CGPointMake(19.84, 2.4)];
        [bezier2Path addLineToPoint: CGPointMake(10.15, 2.4)];
        [bezier2Path addCurveToPoint: CGPointMake(6.74, 5.17) controlPoint1: CGPointMake(8.48, 2.4) controlPoint2: CGPointMake(7.08, 3.59)];
        [bezier2Path addLineToPoint: CGPointMake(5.76, 5.17)];
        [bezier2Path addCurveToPoint: CGPointMake(2.28, 8.65) controlPoint1: CGPointMake(3.85, 5.17) controlPoint2: CGPointMake(2.29, 6.73)];
        [bezier2Path addCurveToPoint: CGPointMake(2.27, 8.68) controlPoint1: CGPointMake(2.28, 8.66) controlPoint2: CGPointMake(2.27, 8.67)];
        [bezier2Path addCurveToPoint: CGPointMake(2.27, 8.69) controlPoint1: CGPointMake(2.27, 8.68) controlPoint2: CGPointMake(2.27, 8.69)];
        [bezier2Path addLineToPoint: CGPointMake(2.27, 9.23)];
        [bezier2Path addCurveToPoint: CGPointMake(2.29, 9.38) controlPoint1: CGPointMake(2.27, 9.28) controlPoint2: CGPointMake(2.28, 9.33)];
        [bezier2Path addCurveToPoint: CGPointMake(3.96, 11.06) controlPoint1: CGPointMake(2.36, 10.28) controlPoint2: CGPointMake(3.07, 10.99)];
        [bezier2Path addCurveToPoint: CGPointMake(4.11, 11.08) controlPoint1: CGPointMake(4.01, 11.07) controlPoint2: CGPointMake(4.06, 11.08)];
        [bezier2Path addLineToPoint: CGPointMake(4.66, 11.08)];
        [bezier2Path addLineToPoint: CGPointMake(5.65, 11.08)];
        [bezier2Path addLineToPoint: CGPointMake(9.73, 44.55)];
        [bezier2Path addCurveToPoint: CGPointMake(15.76, 49.77) controlPoint1: CGPointMake(10.18, 47.5) controlPoint2: CGPointMake(12.82, 49.77)];
        [bezier2Path addCurveToPoint: CGPointMake(15.87, 49.77) controlPoint1: CGPointMake(15.8, 49.77) controlPoint2: CGPointMake(15.84, 49.77)];
        [bezier2Path addLineToPoint: CGPointMake(34.04, 49.77)];
        [bezier2Path addCurveToPoint: CGPointMake(40.2, 44.53) controlPoint1: CGPointMake(37.03, 49.82) controlPoint2: CGPointMake(39.75, 47.53)];
        [bezier2Path addLineToPoint: CGPointMake(44.28, 11.08)];
        [bezier2Path addLineToPoint: CGPointMake(45.27, 11.08)];
        [bezier2Path addLineToPoint: CGPointMake(45.83, 11.08)];
        [bezier2Path addCurveToPoint: CGPointMake(45.97, 11.06) controlPoint1: CGPointMake(45.88, 11.08) controlPoint2: CGPointMake(45.93, 11.07)];
        [bezier2Path addCurveToPoint: CGPointMake(47.64, 9.38) controlPoint1: CGPointMake(46.87, 10.99) controlPoint2: CGPointMake(47.57, 10.28)];
        [bezier2Path addCurveToPoint: CGPointMake(47.66, 9.23) controlPoint1: CGPointMake(47.65, 9.33) controlPoint2: CGPointMake(47.66, 9.28)];
        [bezier2Path addLineToPoint: CGPointMake(47.66, 8.68)];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(21.67, 1.49)];
        [bezier2Path addLineToPoint: CGPointMake(28.26, 1.49)];
        [bezier2Path addCurveToPoint: CGPointMake(28.62, 1.85) controlPoint1: CGPointMake(28.46, 1.49) controlPoint2: CGPointMake(28.62, 1.65)];
        [bezier2Path addLineToPoint: CGPointMake(28.62, 2.4)];
        [bezier2Path addLineToPoint: CGPointMake(21.31, 2.4)];
        [bezier2Path addLineToPoint: CGPointMake(21.31, 1.85)];
        [bezier2Path addCurveToPoint: CGPointMake(21.67, 1.49) controlPoint1: CGPointMake(21.31, 1.65) controlPoint2: CGPointMake(21.48, 1.49)];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(5.76, 6.65)];
        [bezier2Path addLineToPoint: CGPointMake(7.38, 6.65)];
        [bezier2Path addCurveToPoint: CGPointMake(7.4, 6.66) controlPoint1: CGPointMake(7.39, 6.65) controlPoint2: CGPointMake(7.39, 6.66)];
        [bezier2Path addCurveToPoint: CGPointMake(7.69, 6.6) controlPoint1: CGPointMake(7.5, 6.66) controlPoint2: CGPointMake(7.6, 6.63)];
        [bezier2Path addCurveToPoint: CGPointMake(7.87, 6.48) controlPoint1: CGPointMake(7.75, 6.57) controlPoint2: CGPointMake(7.82, 6.52)];
        [bezier2Path addCurveToPoint: CGPointMake(7.92, 6.44) controlPoint1: CGPointMake(7.89, 6.46) controlPoint2: CGPointMake(7.91, 6.45)];
        [bezier2Path addCurveToPoint: CGPointMake(7.96, 6.39) controlPoint1: CGPointMake(7.94, 6.42) controlPoint2: CGPointMake(7.95, 6.41)];
        [bezier2Path addCurveToPoint: CGPointMake(8.14, 5.91) controlPoint1: CGPointMake(8.07, 6.26) controlPoint2: CGPointMake(8.14, 6.1)];
        [bezier2Path addCurveToPoint: CGPointMake(10.15, 3.89) controlPoint1: CGPointMake(8.14, 4.8) controlPoint2: CGPointMake(9.04, 3.89)];
        [bezier2Path addLineToPoint: CGPointMake(39.79, 3.89)];
        [bezier2Path addCurveToPoint: CGPointMake(41.79, 5.91) controlPoint1: CGPointMake(40.89, 3.89) controlPoint2: CGPointMake(41.79, 4.8)];
        [bezier2Path addCurveToPoint: CGPointMake(41.85, 6.19) controlPoint1: CGPointMake(41.79, 6.01) controlPoint2: CGPointMake(41.81, 6.11)];
        [bezier2Path addLineToPoint: CGPointMake(41.85, 6.2)];
        [bezier2Path addCurveToPoint: CGPointMake(41.88, 6.26) controlPoint1: CGPointMake(41.86, 6.22) controlPoint2: CGPointMake(41.87, 6.24)];
        [bezier2Path addCurveToPoint: CGPointMake(42.01, 6.44) controlPoint1: CGPointMake(41.92, 6.32) controlPoint2: CGPointMake(41.96, 6.38)];
        [bezier2Path addCurveToPoint: CGPointMake(42.08, 6.5) controlPoint1: CGPointMake(42.03, 6.46) controlPoint2: CGPointMake(42.06, 6.48)];
        [bezier2Path addCurveToPoint: CGPointMake(42.53, 6.65) controlPoint1: CGPointMake(42.21, 6.59) controlPoint2: CGPointMake(42.36, 6.65)];
        [bezier2Path addLineToPoint: CGPointMake(44.18, 6.65)];
        [bezier2Path addCurveToPoint: CGPointMake(46.19, 8.67) controlPoint1: CGPointMake(45.28, 6.65) controlPoint2: CGPointMake(46.18, 7.56)];
        [bezier2Path addCurveToPoint: CGPointMake(46.18, 8.68) controlPoint1: CGPointMake(46.19, 8.67) controlPoint2: CGPointMake(46.18, 8.67)];
        [bezier2Path addCurveToPoint: CGPointMake(46.19, 8.69) controlPoint1: CGPointMake(46.18, 8.68) controlPoint2: CGPointMake(46.19, 8.69)];
        [bezier2Path addLineToPoint: CGPointMake(46.19, 9.23)];
        [bezier2Path addCurveToPoint: CGPointMake(45.83, 9.59) controlPoint1: CGPointMake(46.19, 9.43) controlPoint2: CGPointMake(46.02, 9.59)];
        [bezier2Path addLineToPoint: CGPointMake(45.27, 9.59)];
        [bezier2Path addLineToPoint: CGPointMake(43.63, 9.59)];
        [bezier2Path addLineToPoint: CGPointMake(6.31, 9.59)];
        [bezier2Path addLineToPoint: CGPointMake(4.66, 9.59)];
        [bezier2Path addLineToPoint: CGPointMake(4.11, 9.59)];
        [bezier2Path addCurveToPoint: CGPointMake(3.75, 9.23) controlPoint1: CGPointMake(3.91, 9.59) controlPoint2: CGPointMake(3.75, 9.43)];
        [bezier2Path addLineToPoint: CGPointMake(3.75, 8.68)];
        [bezier2Path addCurveToPoint: CGPointMake(5.76, 6.65) controlPoint1: CGPointMake(3.75, 7.56) controlPoint2: CGPointMake(4.65, 6.65)];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(38.74, 44.32)];
        [bezier2Path addCurveToPoint: CGPointMake(34.06, 48.29) controlPoint1: CGPointMake(38.41, 46.55) controlPoint2: CGPointMake(36.3, 48.31)];
        [bezier2Path addLineToPoint: CGPointMake(15.86, 48.29)];
        [bezier2Path addCurveToPoint: CGPointMake(15.78, 48.29) controlPoint1: CGPointMake(15.83, 48.29) controlPoint2: CGPointMake(15.81, 48.29)];
        [bezier2Path addCurveToPoint: CGPointMake(11.2, 44.34) controlPoint1: CGPointMake(13.57, 48.29) controlPoint2: CGPointMake(11.52, 46.53)];
        [bezier2Path addLineToPoint: CGPointMake(7.14, 11.08)];
        [bezier2Path addLineToPoint: CGPointMake(42.79, 11.08)];
        [bezier2Path addLineToPoint: CGPointMake(38.74, 44.32)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;
        
        [color8 setFill];
        [bezier2Path fill];
        
        
        //// Group
        {
            //// Group 2
            {
                //// Bezier 4 Drawing
                UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
                [bezier4Path moveToPoint: CGPointMake(18.21, 44.81)];
                [bezier4Path addCurveToPoint: CGPointMake(17.42, 44.18) controlPoint1: CGPointMake(17.82, 44.81) controlPoint2: CGPointMake(17.47, 44.54)];
                [bezier4Path addLineToPoint: CGPointMake(12.9, 14.14)];
                [bezier4Path addCurveToPoint: CGPointMake(13.58, 13.31) controlPoint1: CGPointMake(12.84, 13.74) controlPoint2: CGPointMake(13.14, 13.37)];
                [bezier4Path addCurveToPoint: CGPointMake(14.49, 13.94) controlPoint1: CGPointMake(14.02, 13.26) controlPoint2: CGPointMake(14.43, 13.54)];
                [bezier4Path addLineToPoint: CGPointMake(19.01, 43.98)];
                [bezier4Path addCurveToPoint: CGPointMake(18.32, 44.8) controlPoint1: CGPointMake(19.07, 44.38) controlPoint2: CGPointMake(18.76, 44.75)];
                [bezier4Path addCurveToPoint: CGPointMake(18.21, 44.81) controlPoint1: CGPointMake(18.29, 44.81) controlPoint2: CGPointMake(18.25, 44.81)];
                [bezier4Path closePath];
                bezier4Path.miterLimit = 4;
                
                [color7 setFill];
                [bezier4Path fill];
            }
            
            
            //// Group 3
            {
                //// Bezier 6 Drawing
                UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
                [bezier6Path moveToPoint: CGPointMake(31.72, 44.81)];
                [bezier6Path addCurveToPoint: CGPointMake(31.61, 44.8) controlPoint1: CGPointMake(31.69, 44.81) controlPoint2: CGPointMake(31.65, 44.81)];
                [bezier6Path addCurveToPoint: CGPointMake(30.93, 43.98) controlPoint1: CGPointMake(31.17, 44.75) controlPoint2: CGPointMake(30.87, 44.38)];
                [bezier6Path addLineToPoint: CGPointMake(35.45, 13.94)];
                [bezier6Path addCurveToPoint: CGPointMake(36.35, 13.31) controlPoint1: CGPointMake(35.51, 13.54) controlPoint2: CGPointMake(35.91, 13.26)];
                [bezier6Path addCurveToPoint: CGPointMake(37.04, 14.14) controlPoint1: CGPointMake(36.79, 13.37) controlPoint2: CGPointMake(37.1, 13.74)];
                [bezier6Path addLineToPoint: CGPointMake(32.52, 44.18)];
                [bezier6Path addCurveToPoint: CGPointMake(31.72, 44.81) controlPoint1: CGPointMake(32.46, 44.54) controlPoint2: CGPointMake(32.12, 44.81)];
                [bezier6Path closePath];
                bezier6Path.miterLimit = 4;
                
                [color6 setFill];
                [bezier6Path fill];
            }
            
            
            //// Group 4
            {
                //// Bezier 8 Drawing
                UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
                [bezier8Path moveToPoint: CGPointMake(24.97, 44.81)];
                [bezier8Path addCurveToPoint: CGPointMake(24.17, 44.08) controlPoint1: CGPointMake(24.53, 44.81) controlPoint2: CGPointMake(24.17, 44.48)];
                [bezier8Path addLineToPoint: CGPointMake(24.17, 14.04)];
                [bezier8Path addCurveToPoint: CGPointMake(24.97, 13.31) controlPoint1: CGPointMake(24.17, 13.64) controlPoint2: CGPointMake(24.53, 13.31)];
                [bezier8Path addCurveToPoint: CGPointMake(25.77, 14.04) controlPoint1: CGPointMake(25.41, 13.31) controlPoint2: CGPointMake(25.77, 13.64)];
                [bezier8Path addLineToPoint: CGPointMake(25.77, 44.08)];
                [bezier8Path addCurveToPoint: CGPointMake(24.97, 44.81) controlPoint1: CGPointMake(25.77, 44.48) controlPoint2: CGPointMake(25.41, 44.81)];
                [bezier8Path closePath];
                bezier8Path.miterLimit = 4;
                
                [color5 setFill];
                [bezier8Path fill];
            }
        }
    }
}

+ (void)drawCanvas1
{
    
    //// Group 3
    {
        //// Group 2
        {
            //// Group
            {
                //// Bezier 8 Drawing
                UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
                [bezier8Path moveToPoint: CGPointMake(27.74, 24.39)];
                [bezier8Path addCurveToPoint: CGPointMake(28.15, 24) controlPoint1: CGPointMake(27.97, 24.39) controlPoint2: CGPointMake(28.15, 24.22)];
                [bezier8Path addCurveToPoint: CGPointMake(36.32, 19.23) controlPoint1: CGPointMake(28.15, 21.46) controlPoint2: CGPointMake(31.97, 19.23)];
                [bezier8Path addCurveToPoint: CGPointMake(36.72, 18.83) controlPoint1: CGPointMake(36.54, 19.23) controlPoint2: CGPointMake(36.72, 19.05)];
                [bezier8Path addCurveToPoint: CGPointMake(36.32, 18.44) controlPoint1: CGPointMake(36.72, 18.61) controlPoint2: CGPointMake(36.54, 18.44)];
                [bezier8Path addCurveToPoint: CGPointMake(27.33, 24) controlPoint1: CGPointMake(31.45, 18.44) controlPoint2: CGPointMake(27.33, 20.98)];
                [bezier8Path addCurveToPoint: CGPointMake(27.74, 24.39) controlPoint1: CGPointMake(27.33, 24.22) controlPoint2: CGPointMake(27.52, 24.39)];
                [bezier8Path closePath];
                bezier8Path.miterLimit = 4;
                
                [UIColor.whiteColor setFill];
                [bezier8Path fill];
                
                
                //// Bezier 10 Drawing
                UIBezierPath* bezier10Path = UIBezierPath.bezierPath;
                [bezier10Path moveToPoint: CGPointMake(28.07, 36.71)];
                [bezier10Path addCurveToPoint: CGPointMake(28.28, 36.7) controlPoint1: CGPointMake(28.15, 36.71) controlPoint2: CGPointMake(28.28, 36.69)];
                [bezier10Path addCurveToPoint: CGPointMake(33.8, 33.35) controlPoint1: CGPointMake(30.83, 36.29) controlPoint2: CGPointMake(33.24, 34.01)];
                [bezier10Path addCurveToPoint: CGPointMake(36.32, 33.53) controlPoint1: CGPointMake(34.61, 33.47) controlPoint2: CGPointMake(35.45, 33.53)];
                [bezier10Path addCurveToPoint: CGPointMake(49.39, 24) controlPoint1: CGPointMake(43.53, 33.53) controlPoint2: CGPointMake(49.39, 29.26)];
                [bezier10Path addCurveToPoint: CGPointMake(36.32, 14.46) controlPoint1: CGPointMake(49.39, 18.73) controlPoint2: CGPointMake(43.53, 14.46)];
                [bezier10Path addCurveToPoint: CGPointMake(27.42, 17.02) controlPoint1: CGPointMake(32.88, 14.46) controlPoint2: CGPointMake(29.75, 15.43)];
                [bezier10Path addCurveToPoint: CGPointMake(27.64, 18.83) controlPoint1: CGPointMake(27.6, 17.73) controlPoint2: CGPointMake(27.64, 18.37)];
                [bezier10Path addCurveToPoint: CGPointMake(36.32, 16.05) controlPoint1: CGPointMake(29.74, 17.13) controlPoint2: CGPointMake(32.85, 16.05)];
                [bezier10Path addCurveToPoint: CGPointMake(47.75, 24) controlPoint1: CGPointMake(42.62, 16.05) controlPoint2: CGPointMake(47.75, 19.62)];
                [bezier10Path addCurveToPoint: CGPointMake(36.32, 31.94) controlPoint1: CGPointMake(47.75, 28.38) controlPoint2: CGPointMake(42.62, 31.94)];
                [bezier10Path addCurveToPoint: CGPointMake(34.03, 31.78) controlPoint1: CGPointMake(35.57, 31.94) controlPoint2: CGPointMake(34.8, 31.89)];
                [bezier10Path addCurveToPoint: CGPointMake(33.8, 31.76) controlPoint1: CGPointMake(33.96, 31.76) controlPoint2: CGPointMake(33.88, 31.76)];
                [bezier10Path addCurveToPoint: CGPointMake(32.53, 32.34) controlPoint1: CGPointMake(33.31, 31.76) controlPoint2: CGPointMake(32.85, 31.97)];
                [bezier10Path addCurveToPoint: CGPointMake(30.01, 34.36) controlPoint1: CGPointMake(32.18, 32.75) controlPoint2: CGPointMake(31.19, 33.68)];
                [bezier10Path addCurveToPoint: CGPointMake(30.6, 32.03) controlPoint1: CGPointMake(30.33, 33.65) controlPoint2: CGPointMake(30.58, 32.85)];
                [bezier10Path addCurveToPoint: CGPointMake(30.61, 31.88) controlPoint1: CGPointMake(30.6, 31.98) controlPoint2: CGPointMake(30.61, 31.93)];
                [bezier10Path addCurveToPoint: CGPointMake(29.72, 30.47) controlPoint1: CGPointMake(30.61, 31.28) controlPoint2: CGPointMake(30.26, 30.74)];
                [bezier10Path addCurveToPoint: CGPointMake(26.75, 28.32) controlPoint1: CGPointMake(28.53, 29.88) controlPoint2: CGPointMake(27.53, 29.14)];
                [bezier10Path addCurveToPoint: CGPointMake(25.93, 29.24) controlPoint1: CGPointMake(26.53, 28.64) controlPoint2: CGPointMake(26.25, 28.95)];
                [bezier10Path addCurveToPoint: CGPointMake(25.87, 29.72) controlPoint1: CGPointMake(25.92, 29.41) controlPoint2: CGPointMake(25.9, 29.56)];
                [bezier10Path addCurveToPoint: CGPointMake(28.97, 31.88) controlPoint1: CGPointMake(26.74, 30.56) controlPoint2: CGPointMake(27.78, 31.29)];
                [bezier10Path addCurveToPoint: CGPointMake(28.97, 31.94) controlPoint1: CGPointMake(28.97, 31.9) controlPoint2: CGPointMake(28.97, 31.92)];
                [bezier10Path addCurveToPoint: CGPointMake(27.39, 35.7) controlPoint1: CGPointMake(28.97, 33.37) controlPoint2: CGPointMake(27.87, 34.9)];
                [bezier10Path addLineToPoint: CGPointMake(27.39, 35.7)];
                [bezier10Path addCurveToPoint: CGPointMake(27.33, 35.99) controlPoint1: CGPointMake(27.36, 35.79) controlPoint2: CGPointMake(27.33, 35.89)];
                [bezier10Path addCurveToPoint: CGPointMake(28.07, 36.71) controlPoint1: CGPointMake(27.33, 36.39) controlPoint2: CGPointMake(27.66, 36.71)];
                [bezier10Path closePath];
                bezier10Path.miterLimit = 4;
                
                [UIColor.whiteColor setFill];
                [bezier10Path fill];
                
                
                //// Bezier 12 Drawing
                UIBezierPath* bezier12Path = UIBezierPath.bezierPath;
                [bezier12Path moveToPoint: CGPointMake(36.29, 48.2)];
                [bezier12Path addCurveToPoint: CGPointMake(29.79, 40.33) controlPoint1: CGPointMake(36.25, 47.96) controlPoint2: CGPointMake(35.18, 42.13)];
                [bezier12Path addCurveToPoint: CGPointMake(23.55, 36.28) controlPoint1: CGPointMake(24, 38.4) controlPoint2: CGPointMake(23.55, 36.74)];
                [bezier12Path addLineToPoint: CGPointMake(23.55, 33.54)];
                [bezier12Path addCurveToPoint: CGPointMake(25.52, 29.72) controlPoint1: CGPointMake(24.05, 33.01) controlPoint2: CGPointMake(25.24, 31.57)];
                [bezier12Path addCurveToPoint: CGPointMake(25.58, 29.25) controlPoint1: CGPointMake(25.55, 29.57) controlPoint2: CGPointMake(25.57, 29.41)];
                [bezier12Path addCurveToPoint: CGPointMake(26.4, 28.32) controlPoint1: CGPointMake(25.9, 28.95) controlPoint2: CGPointMake(26.17, 28.64)];
                [bezier12Path addCurveToPoint: CGPointMake(27.12, 26.65) controlPoint1: CGPointMake(26.78, 27.79) controlPoint2: CGPointMake(27.02, 27.23)];
                [bezier12Path addLineToPoint: CGPointMake(27.14, 26.58)];
                [bezier12Path addCurveToPoint: CGPointMake(26.58, 23.55) controlPoint1: CGPointMake(27.29, 25.72) controlPoint2: CGPointMake(27.48, 24.67)];
                [bezier12Path addCurveToPoint: CGPointMake(27.29, 19.43) controlPoint1: CGPointMake(26.86, 22.4) controlPoint2: CGPointMake(27.29, 20.21)];
                [bezier12Path addLineToPoint: CGPointMake(27.29, 19.31)];
                [bezier12Path addCurveToPoint: CGPointMake(27.29, 18.83) controlPoint1: CGPointMake(27.29, 19.19) controlPoint2: CGPointMake(27.3, 19.03)];
                [bezier12Path addCurveToPoint: CGPointMake(27.07, 17.02) controlPoint1: CGPointMake(27.29, 18.37) controlPoint2: CGPointMake(27.24, 17.73)];
                [bezier12Path addCurveToPoint: CGPointMake(26.06, 14.78) controlPoint1: CGPointMake(26.9, 16.31) controlPoint2: CGPointMake(26.59, 15.53)];
                [bezier12Path addCurveToPoint: CGPointMake(23.29, 13.18) controlPoint1: CGPointMake(25.47, 13.96) controlPoint2: CGPointMake(24.41, 13.58)];
                [bezier12Path addCurveToPoint: CGPointMake(22.48, 12.88) controlPoint1: CGPointMake(23.03, 13.09) controlPoint2: CGPointMake(22.75, 12.99)];
                [bezier12Path addCurveToPoint: CGPointMake(21.74, 12.56) controlPoint1: CGPointMake(22.24, 12.79) controlPoint2: CGPointMake(22, 12.68)];
                [bezier12Path addCurveToPoint: CGPointMake(18.32, 11.7) controlPoint1: CGPointMake(20.86, 12.16) controlPoint2: CGPointMake(19.87, 11.7)];
                [bezier12Path addCurveToPoint: CGPointMake(11.23, 14.01) controlPoint1: CGPointMake(15.15, 11.7) controlPoint2: CGPointMake(12.77, 12.48)];
                [bezier12Path addCurveToPoint: CGPointMake(9.35, 19.31) controlPoint1: CGPointMake(9.92, 15.32) controlPoint2: CGPointMake(9.29, 17.1)];
                [bezier12Path addLineToPoint: CGPointMake(9.35, 19.43)];
                [bezier12Path addCurveToPoint: CGPointMake(10.06, 23.55) controlPoint1: CGPointMake(9.35, 20.21) controlPoint2: CGPointMake(9.78, 22.39)];
                [bezier12Path addCurveToPoint: CGPointMake(9.5, 26.58) controlPoint1: CGPointMake(9.16, 24.67) controlPoint2: CGPointMake(9.35, 25.72)];
                [bezier12Path addLineToPoint: CGPointMake(9.51, 26.65)];
                [bezier12Path addCurveToPoint: CGPointMake(11.06, 29.24) controlPoint1: CGPointMake(9.68, 27.58) controlPoint2: CGPointMake(10.2, 28.45)];
                [bezier12Path addCurveToPoint: CGPointMake(13.09, 33.54) controlPoint1: CGPointMake(11.19, 31.31) controlPoint2: CGPointMake(12.55, 32.96)];
                [bezier12Path addLineToPoint: CGPointMake(13.09, 36.28)];
                [bezier12Path addCurveToPoint: CGPointMake(6.85, 40.33) controlPoint1: CGPointMake(13.09, 36.74) controlPoint2: CGPointMake(12.64, 38.4)];
                [bezier12Path addCurveToPoint: CGPointMake(0.34, 48.2) controlPoint1: CGPointMake(1.46, 42.13) controlPoint2: CGPointMake(0.39, 47.96)];
                [bezier12Path addLineToPoint: CGPointMake(0.2, 49)];
                [bezier12Path addLineToPoint: CGPointMake(36.43, 49)];
                [bezier12Path addLineToPoint: CGPointMake(36.29, 48.2)];
                [bezier12Path closePath];
                [bezier12Path moveToPoint: CGPointMake(14.49, 36.28)];
                [bezier12Path addLineToPoint: CGPointMake(14.49, 32.98)];
                [bezier12Path addLineToPoint: CGPointMake(14.28, 32.78)];
                [bezier12Path addCurveToPoint: CGPointMake(12.45, 28.94) controlPoint1: CGPointMake(14.26, 32.76) controlPoint2: CGPointMake(12.45, 31.04)];
                [bezier12Path addLineToPoint: CGPointMake(12.45, 28.63)];
                [bezier12Path addLineToPoint: CGPointMake(12.21, 28.42)];
                [bezier12Path addCurveToPoint: CGPointMake(10.9, 26.41) controlPoint1: CGPointMake(11.46, 27.78) controlPoint2: CGPointMake(11.02, 27.11)];
                [bezier12Path addLineToPoint: CGPointMake(10.88, 26.34)];
                [bezier12Path addCurveToPoint: CGPointMake(11.34, 24.19) controlPoint1: CGPointMake(10.74, 25.52) controlPoint2: CGPointMake(10.63, 24.92)];
                [bezier12Path addLineToPoint: CGPointMake(11.6, 23.91)];
                [bezier12Path addLineToPoint: CGPointMake(11.51, 23.55)];
                [bezier12Path addCurveToPoint: CGPointMake(10.76, 19.43) controlPoint1: CGPointMake(11.21, 22.45) controlPoint2: CGPointMake(10.76, 20.05)];
                [bezier12Path addCurveToPoint: CGPointMake(10.75, 19.27) controlPoint1: CGPointMake(10.76, 19.39) controlPoint2: CGPointMake(10.75, 19.34)];
                [bezier12Path addCurveToPoint: CGPointMake(12.24, 14.96) controlPoint1: CGPointMake(10.73, 18.59) controlPoint2: CGPointMake(10.68, 16.52)];
                [bezier12Path addCurveToPoint: CGPointMake(18.32, 13.06) controlPoint1: CGPointMake(13.5, 13.7) controlPoint2: CGPointMake(15.55, 13.06)];
                [bezier12Path addCurveToPoint: CGPointMake(21.14, 13.79) controlPoint1: CGPointMake(19.55, 13.06) controlPoint2: CGPointMake(20.32, 13.42)];
                [bezier12Path addCurveToPoint: CGPointMake(21.96, 14.15) controlPoint1: CGPointMake(21.41, 13.92) controlPoint2: CGPointMake(21.68, 14.04)];
                [bezier12Path addCurveToPoint: CGPointMake(22.81, 14.46) controlPoint1: CGPointMake(22.25, 14.26) controlPoint2: CGPointMake(22.53, 14.36)];
                [bezier12Path addCurveToPoint: CGPointMake(24.91, 15.56) controlPoint1: CGPointMake(23.71, 14.79) controlPoint2: CGPointMake(24.57, 15.09)];
                [bezier12Path addCurveToPoint: CGPointMake(25.83, 17.98) controlPoint1: CGPointMake(25.49, 16.37) controlPoint2: CGPointMake(25.73, 17.26)];
                [bezier12Path addCurveToPoint: CGPointMake(25.89, 19.27) controlPoint1: CGPointMake(25.9, 18.56) controlPoint2: CGPointMake(25.89, 19.03)];
                [bezier12Path addCurveToPoint: CGPointMake(25.88, 19.43) controlPoint1: CGPointMake(25.88, 19.34) controlPoint2: CGPointMake(25.88, 19.39)];
                [bezier12Path addCurveToPoint: CGPointMake(25.77, 20.4) controlPoint1: CGPointMake(25.88, 19.62) controlPoint2: CGPointMake(25.84, 19.97)];
                [bezier12Path addCurveToPoint: CGPointMake(25.13, 23.55) controlPoint1: CGPointMake(25.62, 21.39) controlPoint2: CGPointMake(25.34, 22.79)];
                [bezier12Path addLineToPoint: CGPointMake(25.03, 23.91)];
                [bezier12Path addLineToPoint: CGPointMake(25.3, 24.19)];
                [bezier12Path addCurveToPoint: CGPointMake(25.75, 26.34) controlPoint1: CGPointMake(26.01, 24.92) controlPoint2: CGPointMake(25.9, 25.52)];
                [bezier12Path addLineToPoint: CGPointMake(25.74, 26.41)];
                [bezier12Path addCurveToPoint: CGPointMake(25.49, 27.15) controlPoint1: CGPointMake(25.7, 26.66) controlPoint2: CGPointMake(25.61, 26.9)];
                [bezier12Path addCurveToPoint: CGPointMake(24.42, 28.42) controlPoint1: CGPointMake(25.26, 27.58) controlPoint2: CGPointMake(24.91, 28.01)];
                [bezier12Path addLineToPoint: CGPointMake(24.4, 28.44)];
                [bezier12Path addLineToPoint: CGPointMake(24.18, 28.63)];
                [bezier12Path addLineToPoint: CGPointMake(24.18, 28.94)];
                [bezier12Path addCurveToPoint: CGPointMake(22.36, 32.78) controlPoint1: CGPointMake(24.18, 31.03) controlPoint2: CGPointMake(22.38, 32.76)];
                [bezier12Path addLineToPoint: CGPointMake(22.15, 32.98)];
                [bezier12Path addLineToPoint: CGPointMake(22.15, 36.28)];
                [bezier12Path addCurveToPoint: CGPointMake(29.34, 41.62) controlPoint1: CGPointMake(22.15, 38.23) controlPoint2: CGPointMake(24.56, 40.03)];
                [bezier12Path addCurveToPoint: CGPointMake(34.7, 47.63) controlPoint1: CGPointMake(32.83, 42.79) controlPoint2: CGPointMake(34.23, 46.1)];
                [bezier12Path addLineToPoint: CGPointMake(1.93, 47.63)];
                [bezier12Path addCurveToPoint: CGPointMake(7.3, 41.62) controlPoint1: CGPointMake(2.4, 46.1) controlPoint2: CGPointMake(3.79, 42.79)];
                [bezier12Path addCurveToPoint: CGPointMake(14.49, 36.28) controlPoint1: CGPointMake(12.07, 40.03) controlPoint2: CGPointMake(14.49, 38.23)];
                [bezier12Path closePath];
                bezier12Path.miterLimit = 4;
                
                [UIColor.whiteColor setFill];
                [bezier12Path fill];
            }
        }
    }
}

+ (void)drawCanvas2
{
    //// Color Declarations
    UIColor* color10 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(9.43, 3.88)];
        [bezier2Path addLineToPoint: CGPointMake(5.23, 2.54)];
        [bezier2Path addCurveToPoint: CGPointMake(5.16, 2.54) controlPoint1: CGPointMake(5.21, 2.53) controlPoint2: CGPointMake(5.19, 2.53)];
        [bezier2Path addLineToPoint: CGPointMake(0.97, 3.88)];
        [bezier2Path addCurveToPoint: CGPointMake(0.88, 4.01) controlPoint1: CGPointMake(0.92, 3.89) controlPoint2: CGPointMake(0.88, 3.95)];
        [bezier2Path addCurveToPoint: CGPointMake(0.97, 4.14) controlPoint1: CGPointMake(0.88, 4.07) controlPoint2: CGPointMake(0.92, 4.12)];
        [bezier2Path addLineToPoint: CGPointMake(2.56, 4.65)];
        [bezier2Path addLineToPoint: CGPointMake(2.56, 5.8)];
        [bezier2Path addCurveToPoint: CGPointMake(5.2, 6.81) controlPoint1: CGPointMake(2.56, 6.45) controlPoint2: CGPointMake(3.92, 6.81)];
        [bezier2Path addCurveToPoint: CGPointMake(7.84, 5.8) controlPoint1: CGPointMake(6.48, 6.81) controlPoint2: CGPointMake(7.84, 6.45)];
        [bezier2Path addLineToPoint: CGPointMake(7.84, 4.65)];
        [bezier2Path addLineToPoint: CGPointMake(9.43, 4.14)];
        [bezier2Path addCurveToPoint: CGPointMake(9.52, 4.01) controlPoint1: CGPointMake(9.48, 4.12) controlPoint2: CGPointMake(9.52, 4.07)];
        [bezier2Path addCurveToPoint: CGPointMake(9.43, 3.88) controlPoint1: CGPointMake(9.52, 3.95) controlPoint2: CGPointMake(9.48, 3.89)];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(7.59, 5.8)];
        [bezier2Path addCurveToPoint: CGPointMake(5.2, 6.53) controlPoint1: CGPointMake(7.59, 6.1) controlPoint2: CGPointMake(6.68, 6.53)];
        [bezier2Path addCurveToPoint: CGPointMake(2.81, 5.8) controlPoint1: CGPointMake(3.72, 6.53) controlPoint2: CGPointMake(2.81, 6.1)];
        [bezier2Path addLineToPoint: CGPointMake(2.81, 4.73)];
        [bezier2Path addLineToPoint: CGPointMake(5.16, 5.48)];
        [bezier2Path addCurveToPoint: CGPointMake(5.2, 5.49) controlPoint1: CGPointMake(5.18, 5.48) controlPoint2: CGPointMake(5.19, 5.49)];
        [bezier2Path addCurveToPoint: CGPointMake(5.23, 5.48) controlPoint1: CGPointMake(5.21, 5.49) controlPoint2: CGPointMake(5.22, 5.48)];
        [bezier2Path addLineToPoint: CGPointMake(7.59, 4.73)];
        [bezier2Path addLineToPoint: CGPointMake(7.59, 5.8)];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(5.2, 5.2)];
        [bezier2Path addLineToPoint: CGPointMake(1.45, 4.01)];
        [bezier2Path addLineToPoint: CGPointMake(5.2, 2.81)];
        [bezier2Path addLineToPoint: CGPointMake(8.94, 4.01)];
        [bezier2Path addLineToPoint: CGPointMake(5.2, 5.2)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;
        
        [color10 setFill];
        [bezier2Path fill];
        
        
        //// Bezier 4 Drawing
        UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
        [bezier4Path moveToPoint: CGPointMake(8.63, 5.78)];
        [bezier4Path addLineToPoint: CGPointMake(8.63, 4.91)];
        [bezier4Path addCurveToPoint: CGPointMake(7.97, 4.11) controlPoint1: CGPointMake(8.64, 4.5) controlPoint2: CGPointMake(8.34, 4.13)];
        [bezier4Path addLineToPoint: CGPointMake(5.21, 3.87)];
        [bezier4Path addCurveToPoint: CGPointMake(5.07, 4) controlPoint1: CGPointMake(5.14, 3.86) controlPoint2: CGPointMake(5.08, 3.92)];
        [bezier4Path addCurveToPoint: CGPointMake(5.19, 4.15) controlPoint1: CGPointMake(5.07, 4.07) controlPoint2: CGPointMake(5.12, 4.14)];
        [bezier4Path addLineToPoint: CGPointMake(7.95, 4.38)];
        [bezier4Path addCurveToPoint: CGPointMake(8.39, 4.91) controlPoint1: CGPointMake(8.19, 4.4) controlPoint2: CGPointMake(8.39, 4.64)];
        [bezier4Path addLineToPoint: CGPointMake(8.39, 5.78)];
        [bezier4Path addCurveToPoint: CGPointMake(8.24, 6.05) controlPoint1: CGPointMake(8.3, 5.83) controlPoint2: CGPointMake(8.24, 5.94)];
        [bezier4Path addCurveToPoint: CGPointMake(8.51, 6.91) controlPoint1: CGPointMake(8.24, 6.22) controlPoint2: CGPointMake(8.36, 6.91)];
        [bezier4Path addCurveToPoint: CGPointMake(8.78, 6.05) controlPoint1: CGPointMake(8.66, 6.91) controlPoint2: CGPointMake(8.78, 6.22)];
        [bezier4Path addCurveToPoint: CGPointMake(8.63, 5.78) controlPoint1: CGPointMake(8.78, 5.94) controlPoint2: CGPointMake(8.72, 5.83)];
        [bezier4Path closePath];
        bezier4Path.miterLimit = 4;
        
        [color10 setFill];
        [bezier4Path fill];
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfFeedback
{
    if (_imageOfFeedback)
        return _imageOfFeedback;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(50, 50), NO, 0.0f);
    [SettingsIcons drawFeedback];
    
    _imageOfFeedback = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return _imageOfFeedback;
}

+ (UIImage*)imageOfTutorial
{
    if (_imageOfTutorial)
        return _imageOfTutorial;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(50, 50), NO, 0.0f);
    [SettingsIcons drawTutorial];
    
    _imageOfTutorial = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return _imageOfTutorial;
}

+ (UIImage*)imageOfTrash
{
    if (_imageOfTrash)
        return _imageOfTrash;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(50, 50), NO, 0.0f);
    [SettingsIcons drawTrash];
    
    _imageOfTrash = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return _imageOfTrash;
}

+ (UIImage*)imageOfCanvas1
{
    if (_imageOfCanvas1)
        return _imageOfCanvas1;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(50, 50), NO, 0.0f);
    [SettingsIcons drawCanvas1];
    
    _imageOfCanvas1 = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return _imageOfCanvas1;
}

+ (UIImage*)imageOfCanvas2
{
    if (_imageOfCanvas2)
        return _imageOfCanvas2;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 10), NO, 0.0f);
    [SettingsIcons drawCanvas2];
    
    _imageOfCanvas2 = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return _imageOfCanvas2;
}

#pragma mark Customization Infrastructure

- (void)setFeedbackTargets: (NSArray*)feedbackTargets
{
    _feedbackTargets = feedbackTargets;
    
    for (id target in self.feedbackTargets)
        [target setImage: SettingsIcons.imageOfFeedback];
}

- (void)setTutorialTargets: (NSArray*)tutorialTargets
{
    _tutorialTargets = tutorialTargets;
    
    for (id target in self.tutorialTargets)
        [target setImage: SettingsIcons.imageOfTutorial];
}

- (void)setTrashTargets: (NSArray*)trashTargets
{
    _trashTargets = trashTargets;
    
    for (id target in self.trashTargets)
        [target setImage: SettingsIcons.imageOfTrash];
}

- (void)setCanvas1Targets: (NSArray*)canvas1Targets
{
    _canvas1Targets = canvas1Targets;
    
    for (id target in self.canvas1Targets)
        [target setImage: SettingsIcons.imageOfCanvas1];
}

- (void)setCanvas2Targets: (NSArray*)canvas2Targets
{
    _canvas2Targets = canvas2Targets;
    
    for (id target in self.canvas2Targets)
        [target setImage: SettingsIcons.imageOfCanvas2];
}

+ (UIImage *)imageWithImage:(UIImage *)image scaledToSize: (CGRect)rect
{
    UIGraphicsBeginImageContext(rect.size);
    [image drawInRect:CGRectMake(0, 0, rect.size.width, rect.size.height)];
    UIImage *newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return newImage;
}


@end
