# SwiftLint Configuration for Trivit

# Paths to include for linting
included:
  - Trivit
  - TrivitTests
  - TrivitUITests

# Paths to exclude from linting
excluded:
  - Pods
  - .build
  - DerivedData
  - Package.swift
  - trivit  # Old Objective-C code
  - trivitWatchKitExtension
  - trivit Watch App
  - DataKit

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Can be noisy
  - todo  # We use TODO comments intentionally
  - opening_brace  # Conflicts with swift-format
  - nesting  # Sometimes deep nesting is necessary

# Enabled optional rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule configurations

# Line length
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Type body length
type_body_length:
  warning: 300
  error: 500

# Function body length
function_body_length:
  warning: 50
  error: 100

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Type name
type_name:
  min_length: 3
  max_length: 50
  validates_start_with_lowercase: false
  allowed_symbols: []
  excluded:
    - ID
    - URL
    - UI

# Identifier name
identifier_name:
  min_length: 1
  max_length: 50
  allowed_symbols: []
  validates_start_with_lowercase: true
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Force cast
force_cast: warning

# Force try
force_try: warning

# Nesting
nesting:
  type_level: 2
  function_level: 3
  check_nesting_in_closures_and_statements: true
  always_allow_one_type_in_functions: false

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Trailing comma
trailing_comma:
  mandatory_comma: false

# Modifier order
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutating
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

# Custom rules
custom_rules:
  no_print:
    included: ".*\\.swift"
    excluded: ".*Tests?\\.swift"
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use a logging framework instead of print()"
    severity: warning

  no_force_unwrap_in_tests:
    included: ".*Tests?\\.swift"
    name: "Prefer #expect over XCTAssert in Swift Testing"
    regex: "XCTAssert"
    message: "Consider using #expect from Swift Testing instead of XCTAssert"
    severity: warning

  mark_comment_spacing:
    name: "MARK Comment Spacing"
    regex: "// MARK:[^ ]"
    message: "MARK comments should have a space after the colon"
    severity: warning

# Reporter
reporter: xcode
