name: Trivit
options:
  bundleIdPrefix: be.ballooninc
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
    watchOS: "10.0"
  xcodeVersion: "17.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "3.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_COMPILATION_MODE: wholemodule

targets:
  Trivit:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: Trivit
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: be.ballooninc.trivit
        INFOPLIST_FILE: Trivit/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Trivit/Resources/Trivit.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: Trivit
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
    entitlements:
      path: Trivit/Resources/Trivit.entitlements
    info:
      path: Trivit/Resources/Info.plist
      properties:
        CFBundleDisplayName: Trivit
        CFBundleName: Trivit
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        NSLocationWhenInUseUsageDescription: "Trivit uses your location for location-based reminders."
        NSLocationAlwaysAndWhenInUseUsageDescription: "Trivit uses your location for location-based reminders even when the app is in the background."
        UIBackgroundModes:
          - fetch
          - remote-notification
          - location
    scheme:
      testTargets:
        - TrivitTests
        - TrivitUITests
      gatherCoverageData: true
      testPlans:
        - path: TrivitTests/UnitTests.xctestplan
          defaultPlan: true
        - path: TrivitUITests/UITests.xctestplan
        - path: TrivitUITests/iPadUITests.xctestplan
        - path: TrivitUITests/macOSUITests.xctestplan

  TrivitTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources:
      - path: TrivitTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Trivit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: be.ballooninc.trivit.tests
        INFOPLIST_FILE: TrivitTests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Trivit.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Trivit"
        BUNDLE_LOADER: "$(TEST_HOST)"

  TrivitUITests:
    type: bundle.ui-testing
    platform: [iOS, macOS]
    sources:
      - path: TrivitUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Trivit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: be.ballooninc.trivit.uitests
        INFOPLIST_FILE: TrivitUITests/Info.plist
        TEST_TARGET_NAME: Trivit

schemes:
  Trivit:
    build:
      targets:
        Trivit: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: TrivitTests
          parallelizable: true
          randomExecutionOrder: true
        - name: TrivitUITests
          parallelizable: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
